from asciimatics.screen import Screen

DEFAULT=Screen.COLOUR_DEFAULT
BLACK=Screen.COLOUR_BLACK
RED=Screen.COLOUR_RED
GREEN=Screen.COLOUR_GREEN
YELLOW=Screen.COLOUR_YELLOW
BLUE=Screen.COLOUR_BLUE
MAGENTA=Screen.COLOUR_MAGENTA
CYAN=Screen.COLOUR_CYAN
WHITE=Screen.COLOUR_WHITE

COLOURS=[RED,
         GREEN,
         YELLOW,
         BLUE,
         MAGENTA,
         CYAN]
         
NUM_COLOURS = len(COLOURS)        
